### ISSUE TITLE
Scrape traffic-index

### ISSUE THREAD

**Issue by serhii73** [serhii73/place_to_live#8]
Scrape https://www.tomtom.com/en_gb/traffic-index/ranking/ ,use data for where.py script

**Comment by HAKSOAT** [comment]
I'm interested in working on this. I don't know Scrapy though, so I'll need to wrap my head around it first.

**Comment by serhii73** [comment]
Hello, @HAKSOAT thank you very much for your interest in this project.
https://github.com/serhii73/place_to_live/pull/9
I created a branch for this task - feature/scrape_traffic_index
Please read this page - https://docs.scrapy.org/en/latest/intro/tutorial.html and I think you will understand how to start with Scrapy.
If will be any question, please write to me here or on this webpage https://github.com/serhii73/place_to_live/pull/9

**Comment by HAKSOAT** [comment]
Thanks. I'll check it up.

**Comment by HAKSOAT** [comment]
For the traffic index, the site has the metrics by cities, and not countries. How do you suggest I go about those?

**Comment by serhii73** [comment]
I just want the only table from this webpage https://www.tomtom.com/en_gb/traffic-index/ranking/
I want only items(https://docs.scrapy.org/en/latest/topics/items.html) like 
1. WORLD RANK
2. CITY
3. COUNTRY
I think it will be like 
```
class TrafficIndexItem(Item):
    world_rank = Field()
    city = Field()
    country = Field()
```
You need to change this file https://github.com/serhii73/place_to_live/blob/feature/scrape_traffic_index/traffic_index/traffic_index/items.py for write scrapy items.

**Comment by HAKSOAT** [comment]
I've worked on this. Yet to implement in where.py though, what format should be used? From what I see with "city," it asks certain questions and gives insight based on the answers.

**Comment by serhii73** [comment]
This issue about scrapy and https://www.tomtom.com/en_gb/traffic-index/ranking/, to implement a traffic index in `where.py` need to create a new issue.
